image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

pages:
  stage: deploy
  script:
  - mkdir public
  - mv ./index.html ./public/
  artifacts:
    paths:
    - public
  only:
  - master
