# Site settings
title: Christian Pauly - Personal Website
description: Welcome on my website.
baseurl: "/"
url: "/" # the base hostname & protocol for your site
gitlab_username:  christianpauly

# User settings
username: Christian Pauly
user_description: Hi, my name is Christian Pauly and I'm a software developer from germany. I love frontend developing for apps and webapps, RESTful APIs and Matrix.
user_title: Software Developer
github_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['README.md', 'LICENSE.txt', 'package.json', 'src' , 'node_modules']
